# Generated by Django 5.2.17 on 2026-09-17 17:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Đang trò chuyện'), ('order_placed', 'Đã chốt đơn'), ('closed', 'Đã đóng')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Danh sách phiên chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Mã SKU')),
                ('category', models.CharField(default='Chung', max_length=100, verbose_name='Danh mục')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá niêm yết (VNĐ)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá khuyến mãi (VNĐ)')),
                ('stock', models.IntegerField(default=10, verbose_name='Số lượng tồn kho')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('selling_points', models.TextField(blank=True, help_text='Các điểm bán hàng vượt trội (USP), quà tặng kèm, ưu đãi đặc biệt để AI thuyết phục khách', verbose_name='Điểm nhấn bán hàng (USP)')),
                ('faq', models.TextField(blank=True, help_text='Câu hỏi thường gặp và giải đáp mẫu', verbose_name='FAQ thường gặp')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Đường dẫn ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Danh sách sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Khách hàng'), ('assistant', 'AI Sales Rep'), ('system', 'Hệ thống')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sales_core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Số điện thoại')),
                ('customer_address', models.TextField(verbose_name='Địa chỉ nhận hàng')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã chốt đơn'), ('SHIPPING', 'Đang giao hàng'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã hủy')], default='CONFIRMED', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú đơn hàng')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Đã gửi email thông báo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian tạo')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sales_core.chatsession')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_core.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_core.product')),
            ],
        ),
    ]
