# Generated by Django 5.2.17 on 2026-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='vi', max_length=10, verbose_name='Ngôn ngữ'),
        ),
    ]
